[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/products.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/admin-selina/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
